'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { useEmailAccounts } from '@/hooks/use-email-settings';
import { useUpdateAgent } from '@/hooks/use-agents';
import { useToast } from '@/hooks/use-toast';
import type { MasterAgent } from '@/types';

export function AgentSettingsTab({ agent }: { agent: MasterAgent }) {
  const { data: accountsRaw = [] } = useEmailAccounts();
  const accounts = accountsRaw.filter((a) => a.isActive);
  const update = useUpdateAgent();
  const { toast } = useToast();

  const config = (agent.config ?? {}) as Record<string, unknown>;
  const currentId = (config.emailAccountId as string | undefined) ?? '';
  const [selected, setSelected] = useState<string>(currentId);

  const dirty = selected !== currentId;

  async function handleSave() {
    let nextConfig: Record<string, unknown>;
    if (selected) {
      nextConfig = { ...config, emailAccountId: selected };
    } else {
      const { emailAccountId: _drop, ...rest } = config;
      nextConfig = rest;
    }
    try {
      await update.mutateAsync({ id: agent.id, config: nextConfig });
      toast({ title: 'Settings saved' });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to save settings';
      toast({ title: 'Save failed', description: message, variant: 'destructive' });
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm font-medium">Sending email account</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="agent-email-account">Outbound email account</Label>
          {accounts.length > 0 ? (
            <select
              id="agent-email-account"
              value={selected}
              onChange={(e) => setSelected(e.target.value)}
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
            >
              <option value="">Default (auto-select highest priority)</option>
              {accounts.map((account) => (
                <option key={account.id} value={account.id}>
                  {account.name} ({account.fromEmail})
                </option>
              ))}
            </select>
          ) : (
            <p className="text-xs text-muted-foreground">
              No email accounts configured.{' '}
              <a href="/settings/email" className="text-primary underline">
                Settings &gt; Email
              </a>
            </p>
          )}
          <p className="text-xs text-muted-foreground">
            Used as the sender for new and pending drafts generated by this agent.
            Already-sent emails are not affected.
          </p>
        </div>

        <div className="flex justify-end">
          <Button onClick={handleSave} disabled={!dirty || update.isPending}>
            {update.isPending ? 'Saving…' : 'Save changes'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
