import { eq, and } from 'drizzle-orm';
import { BaseAgent } from './base-agent.js';
import { withTenant } from '../config/database.js';
import { replies, emailsSent, campaignContacts, contacts, masterAgents, emailAccounts, emailListenerConfigs } from '../db/schema/index.js';
import { enqueueEmail } from '../tools/email-queue.tool.js';
import { logActivity, ensureDeal, moveDealStage, findStageBySlug } from '../services/crm-activity.service.js';
import { buildSystemPrompt, buildUserPrompt, type ReplyAnalysis } from '../prompts/reply.prompt.js';
import {
  buildSystemPrompt as inboundSystemPrompt,
  buildUserPrompt as inboundUserPrompt,
  type InboundEmailAnalysis,
} from '../prompts/inbound-email.prompt.js';
import { buildSystemPrompt as outreachSystemPrompt } from '../prompts/outreach.prompt.js';
import { emailIntelligenceEngine } from '../tools/email-intelligence.js';
import logger from '../utils/logger.js';

export class ReplyAgent extends BaseAgent {

  /**
   * Shared helper: look up the master agent's configured email account and
   * enqueue an auto-response generated by Claude.
   * Returns true if a response was enqueued, false otherwise.
   */
  private async sendAutoResponse(opts: {
    masterAgentId: string;
    fromEmail: string;
    toEmail: string;
    subject: string | null | undefined;
    contactId?: string;
    replyBody: string;
    promptInstruction: string;
  }): Promise<boolean> {
    try {
      // Load configured email account from master agent config
      let responseFromEmail = opts.fromEmail;
      let emailAccountId: string | undefined;
      const [masterAgent] = await withTenant(this.tenantId, async (tx) => {
        return tx.select({
          config: masterAgents.config,
          description: masterAgents.description,
          mission: masterAgents.mission,
          useCase: masterAgents.useCase,
        }).from(masterAgents)
          .where(and(eq(masterAgents.id, opts.masterAgentId), eq(masterAgents.tenantId, this.tenantId)))
          .limit(1);
      });
      const agentConfig = (masterAgent?.config as Record<string, unknown>) ?? {};
      const configuredEmailAccountId = agentConfig.emailAccountId as string | undefined;
      const emailRules = (agentConfig.emailRules as string[]) ?? undefined;
      const autoResponseContext = masterAgent ? {
        useCase: masterAgent.useCase,
        description: masterAgent.description ?? undefined,
        mission: masterAgent.mission ?? undefined,
        valueProposition: (agentConfig.valueProposition as string) ?? undefined,
        emailRules,
      } : undefined;
      if (configuredEmailAccountId) {
        const [emailAccount] = await withTenant(this.tenantId, async (tx) => {
          return tx.select().from(emailAccounts)
            .where(and(eq(emailAccounts.id, configuredEmailAccountId), eq(emailAccounts.tenantId, this.tenantId), eq(emailAccounts.isActive, true)))
            .limit(1);
        });
        if (emailAccount) {
          responseFromEmail = emailAccount.fromEmail;
          emailAccountId = emailAccount.id;
        }
      }

      const responseText = await this.callClaude(
        outreachSystemPrompt('professional', autoResponseContext),
        opts.promptInstruction,
      );
      await enqueueEmail({
        tenantId: this.tenantId,
        contactId: opts.contactId,
        emailAccountId,
        fromEmail: responseFromEmail,
        toEmail: opts.toEmail,
        subject: `Re: ${opts.subject ?? ''}`,
        body: `<p>${responseText.replace(/\n/g, '<br>')}</p>`,
        masterAgentId: opts.masterAgentId,
      });
      return true;
    } catch (err) {
      logger.warn({ err, tenantId: this.tenantId }, 'Failed to enqueue auto-response');
      return false;
    }
  }
  async execute(input: Record<string, unknown>): Promise<Record<string, unknown>> {
    const { replyId, masterAgentId } = input as { replyId: string; masterAgentId: string };

    logger.info({ tenantId: this.tenantId, replyId }, 'ReplyAgent starting');
    await this.setCurrentAction('reply_processing', `Processing reply ${replyId.slice(0, 8)}`);

    // 1. Load reply with joined data
    const [reply] = await withTenant(this.tenantId, async (tx) => {
      return tx.select().from(replies)
        .where(and(eq(replies.id, replyId), eq(replies.tenantId, this.tenantId)))
        .limit(1);
    });
    if (!reply) throw new Error(`Reply ${replyId} not found`);

    // Handle general inbound emails (not replies to outbound)
    if (reply.isInbound) {
      return this.processGeneralInbound(reply, masterAgentId);
    }

    // Load email sent record
    const emailSentRecord = reply.emailSentId
      ? await withTenant(this.tenantId, async (tx) => {
          return tx.select().from(emailsSent)
            .where(eq(emailsSent.id, reply.emailSentId!))
            .limit(1);
        })
      : [];

    const emailSent = emailSentRecord[0];

    // Load contact
    const [contact] = reply.contactId
      ? await withTenant(this.tenantId, async (tx) => {
          return tx.select().from(contacts)
            .where(and(eq(contacts.id, reply.contactId!), eq(contacts.tenantId, this.tenantId)))
            .limit(1);
        })
      : [];

    const contactId = contact?.id;

    // Load business context from master agent
    const [masterAgentRecord] = await withTenant(this.tenantId, async (tx) => {
      return tx.select({
        description: masterAgents.description,
        mission: masterAgents.mission,
        useCase: masterAgents.useCase,
        config: masterAgents.config,
      }).from(masterAgents)
        .where(and(eq(masterAgents.id, masterAgentId), eq(masterAgents.tenantId, this.tenantId)))
        .limit(1);
    });
    const agentConfig = (masterAgentRecord?.config as Record<string, unknown>) ?? {};
    const emailRules = (agentConfig.emailRules as string[]) ?? undefined;
    const businessContext = masterAgentRecord ? {
      useCase: masterAgentRecord.useCase,
      description: masterAgentRecord.description ?? undefined,
      mission: masterAgentRecord.mission ?? undefined,
      valueProposition: (agentConfig.valueProposition as string) ?? undefined,
      emailRules,
    } : undefined;

    // 2. Classify reply using Together AI
    const analysis = await this.extractJSON<ReplyAnalysis>([
      { role: 'system', content: buildSystemPrompt(businessContext) },
      {
        role: 'user',
        content: buildUserPrompt({
          replyBody: reply.body ?? '',
          originalSubject: emailSent?.subject ?? '',
          contactName: contact ? `${contact.firstName ?? ''} ${contact.lastName ?? ''}`.trim() : undefined,
        }),
      },
    ]);

    // 3. Save classification + sentiment to reply
    await withTenant(this.tenantId, async (tx) => {
      await tx.update(replies)
        .set({
          classification: analysis.classification,
          sentiment: analysis.sentiment,
          autoResponse: analysis.suggestedResponse ?? undefined,
          processedAt: new Date(),
        })
        .where(eq(replies.id, replyId));
    });

    // 4. Load campaignContact if we have email data
    const campaignContactRecord = emailSent?.campaignContactId
      ? await withTenant(this.tenantId, async (tx) => {
          return tx.select().from(campaignContacts)
            .where(eq(campaignContacts.id, emailSent.campaignContactId!))
            .limit(1);
        })
      : [];
    const campaignContact = campaignContactRecord[0];

    let actionTaken: string = analysis.classification;

    // 5. Handle by classification
    switch (analysis.classification) {
      case 'interested': {
        if (contactId) {
          await withTenant(this.tenantId, async (tx) => {
            await tx.update(contacts)
              .set({ status: 'replied', updatedAt: new Date() })
              .where(eq(contacts.id, contactId));
          });
          await this.dispatchNext('action', {
            contactId,
            action: 'schedule_interview',
            masterAgentId,
          });
        }
        if (emailSent?.fromEmail && emailSent?.toEmail) {
          const sent = await this.sendAutoResponse({
            masterAgentId,
            fromEmail: emailSent.fromEmail,
            toEmail: emailSent.toEmail,
            subject: emailSent.subject,
            contactId,
            replyBody: reply.body ?? '',
            promptInstruction: `Write a brief, enthusiastic response to someone who expressed interest in ${businessContext?.description ?? 'our opportunity'}.\n\nTheir reply: ${reply.body}\n\n${analysis.suggestedResponse ? `Suggested angle: ${analysis.suggestedResponse}` : ''}\n\nThank them for their interest and suggest scheduling a time to talk. Keep it warm and professional.`,
          });
          if (sent) actionTaken = 'interested_responded';
        }
        break;
      }

      case 'objection': {
        if (emailSent?.fromEmail && emailSent?.toEmail) {
          const sent = await this.sendAutoResponse({
            masterAgentId,
            fromEmail: emailSent.fromEmail,
            toEmail: emailSent.toEmail,
            subject: emailSent.subject,
            contactId,
            replyBody: reply.body ?? '',
            promptInstruction: `Write a brief, empathetic response to this email objection:\n\nObjection: ${reply.body}\n\n${analysis.suggestedResponse ? `Suggested angle: ${analysis.suggestedResponse}` : ''}`,
          });
          if (sent) actionTaken = 'objection_responded';
        }
        break;
      }

      case 'not_now': {
        if (contactId && campaignContact) {
          // Follow up in 60 days
          await this.dispatchNext('outreach', {
            contactId,
            campaignId: campaignContact.campaignId,
            stepNumber: 1,
            masterAgentId,
          }, { delay: 60 * 86400000 });
        }
        if (emailSent?.fromEmail && emailSent?.toEmail) {
          const sent = await this.sendAutoResponse({
            masterAgentId,
            fromEmail: emailSent.fromEmail,
            toEmail: emailSent.toEmail,
            subject: emailSent.subject,
            contactId,
            replyBody: reply.body ?? '',
            promptInstruction: `Write a brief, polite acknowledgement to someone who said "not right now" to our outreach.\n\nTheir reply: ${reply.body}\n\n${analysis.suggestedResponse ? `Suggested angle: ${analysis.suggestedResponse}` : ''}\n\nAcknowledge their timing, express understanding, and let them know we'll be in touch in the future. Keep it short and respectful.`,
          });
          if (sent) actionTaken = 'not_now_responded';
        }
        break;
      }

      case 'out_of_office': {
        if (contactId && campaignContact && analysis.returnDate) {
          const returnMs = new Date(analysis.returnDate).getTime() - Date.now();
          const delay = Math.max(returnMs + 86400000, 86400000); // at least 1 day after return
          await this.dispatchNext('outreach', {
            contactId,
            campaignId: campaignContact.campaignId,
            stepNumber: 1,
            masterAgentId,
          }, { delay });
        }
        break;
      }

      case 'unsubscribe': {
        if (campaignContact) {
          await withTenant(this.tenantId, async (tx) => {
            await tx.update(campaignContacts)
              .set({ status: 'unsubscribed', lastActionAt: new Date() })
              .where(eq(campaignContacts.id, campaignContact.id));
          });
        }
        if (contactId) {
          await withTenant(this.tenantId, async (tx) => {
            await tx.update(contacts)
              .set({ status: 'archived', updatedAt: new Date() })
              .where(eq(contacts.id, contactId));
          });
        }
        break;
      }

      case 'bounce': {
        const bouncedEmail = contact?.email;
        if (contactId) {
          await withTenant(this.tenantId, async (tx) => {
            await tx.update(contacts)
              .set({ email: undefined, emailVerified: false, updatedAt: new Date() })
              .where(eq(contacts.id, contactId));
          });
          // Only dispatch enrichment if it's in the pipeline
          const [masterAgent] = await withTenant(this.tenantId, async (tx) => {
            return tx.select({ config: masterAgents.config }).from(masterAgents)
              .where(and(eq(masterAgents.id, masterAgentId), eq(masterAgents.tenantId, this.tenantId)))
              .limit(1);
          });
          const enabled = ((masterAgent?.config as Record<string, unknown>)?.enabledAgents as string[]) ?? null;
          if (!enabled || enabled.includes('enrichment')) {
            await this.dispatchNext('enrichment', { contactId, masterAgentId });
          }
        }
        if (bouncedEmail) {
          try {
            const domain = bouncedEmail.split('@')[1];
            if (domain) {
              await emailIntelligenceEngine.recordDeliverySignal(
                bouncedEmail, domain, null, false, 'hard',
                reply?.body?.substring(0, 500),
              );
            }
          } catch (err) {
            logger.debug({ err, contactId }, 'Failed to record bounce signal');
          }
        }
        break;
      }

      case 'other': {
        if (emailSent?.fromEmail && emailSent?.toEmail) {
          const sent = await this.sendAutoResponse({
            masterAgentId,
            fromEmail: emailSent.fromEmail,
            toEmail: emailSent.toEmail,
            subject: emailSent.subject,
            contactId,
            replyBody: reply.body ?? '',
            promptInstruction: `Write a brief, professional response to this email reply that doesn't clearly fit a standard category.\n\nTheir reply: ${reply.body}\n\n${analysis.suggestedResponse ? `Suggested angle: ${analysis.suggestedResponse}` : ''}\n\nThank them for their email and let them know you'll review and get back to them. Keep it short.`,
          });
          if (sent) actionTaken = 'other_responded';
        }
        break;
      }
    }

    // 6. Update campaignContact status
    if (campaignContact) {
      await withTenant(this.tenantId, async (tx) => {
        await tx.update(campaignContacts)
          .set({ status: 'replied', lastActionAt: new Date() })
          .where(eq(campaignContacts.id, campaignContact.id));
      });
    }

    // CRM: Log activity and move deal stage based on classification
    if (contactId) {
      try {
        await logActivity({
          tenantId: this.tenantId,
          contactId,
          masterAgentId,
          type: 'email_replied',
          title: `Reply classified as: ${analysis.classification}`,
          metadata: { replyId, classification: analysis.classification, sentiment: analysis.sentiment },
        });

        // Move deal stage for certain classifications
        const dealResult = await ensureDeal({ tenantId: this.tenantId, contactId, masterAgentId });
        if (analysis.classification === 'interested') {
          const repliedStage = await findStageBySlug(this.tenantId, 'replied');
          if (repliedStage) {
            await moveDealStage({ tenantId: this.tenantId, dealId: dealResult.id, newStageId: repliedStage.id, masterAgentId });
          }
        } else if (analysis.classification === 'unsubscribe') {
          const lostStage = await findStageBySlug(this.tenantId, 'lost');
          if (lostStage) {
            await moveDealStage({ tenantId: this.tenantId, dealId: dealResult.id, newStageId: lostStage.id, masterAgentId });
          }
        }
      } catch (err) {
        logger.warn({ err, contactId }, 'Failed to update CRM for reply');
      }
    }

    await this.emitEvent('email:replied', {
      replyId,
      contactId,
      classification: analysis.classification,
      sentiment: analysis.sentiment,
    });

    this.logActivity('reply_classified', 'completed', {
      inputSummary: `Reply ${replyId.slice(0, 8)}`,
      details: { replyId, classification: analysis.classification, sentiment: analysis.sentiment, actionTaken },
    });
    await this.clearCurrentAction();

    logger.info({ tenantId: this.tenantId, replyId, classification: analysis.classification }, 'ReplyAgent completed');

    return {
      classification: analysis.classification,
      sentiment: analysis.sentiment,
      actionTaken,
    };
  }

  /**
   * Process a general inbound email (not a reply to a known outbound).
   * Classifies with LLM, saves results, and takes CRM actions.
   */
  private async processGeneralInbound(
    reply: typeof replies.$inferSelect,
    masterAgentId: string,
  ): Promise<Record<string, unknown>> {
    const replyId = reply.id;
    const contactId = reply.contactId;

    logger.info({ tenantId: this.tenantId, replyId }, 'Processing general inbound email');

    // Load business context from master agent
    const [masterAgentRecord] = await withTenant(this.tenantId, async (tx) => {
      return tx.select({
        description: masterAgents.description,
        mission: masterAgents.mission,
        useCase: masterAgents.useCase,
        config: masterAgents.config,
      }).from(masterAgents)
        .where(and(eq(masterAgents.id, masterAgentId), eq(masterAgents.tenantId, this.tenantId)))
        .limit(1);
    });
    const maConfig = (masterAgentRecord?.config as Record<string, unknown>) ?? {};
    const inboundEmailRules = (maConfig.emailRules as string[]) ?? undefined;
    const businessContext = masterAgentRecord ? {
      useCase: masterAgentRecord.useCase,
      description: masterAgentRecord.description ?? undefined,
      mission: masterAgentRecord.mission ?? undefined,
      valueProposition: (maConfig.valueProposition as string) ?? undefined,
      emailRules: inboundEmailRules,
    } : undefined;

    // Classify with LLM
    const analysis = await this.extractJSON<InboundEmailAnalysis>([
      { role: 'system', content: inboundSystemPrompt(businessContext) },
      {
        role: 'user',
        content: inboundUserPrompt({
          fromEmail: reply.fromEmail ?? '',
          subject: reply.subject ?? '',
          body: reply.body ?? '',
        }),
      },
    ]);

    // Save classification + sentiment
    await withTenant(this.tenantId, async (tx) => {
      await tx.update(replies)
        .set({
          classification: analysis.classification,
          sentiment: analysis.sentiment,
          processedAt: new Date(),
        })
        .where(eq(replies.id, replyId));
    });

    // Auto-respond to non-spam inbound emails
    let actionTaken: string = analysis.suggestedAction;
    if (analysis.classification !== 'spam' && reply.fromEmail) {
      const bizDesc = businessContext?.description ?? 'our services';
      const promptMap: Record<string, string> = {
        inquiry: `Write a brief, helpful response to someone inquiring about ${bizDesc}.\n\nTheir email: ${reply.body}\n\nThank them for reaching out and let them know how we can help. Keep it professional and concise.`,
        application: businessContext?.useCase === 'sales'
          ? `Write a brief, professional response to someone reaching out about ${bizDesc}.\n\nTheir email: ${reply.body}\n\nThank them for their interest and let them know we'll follow up.`
          : `Write a brief, professional response to a job applicant.\n\nTheir email: ${reply.body}\n\nThank them for their application and let them know we'll review it and get back to them.`,
        partnership: `Write a brief, professional response to a business partnership proposal.\n\nTheir email: ${reply.body}\n\nThank them for the proposal and let them know we'll review it internally.`,
        introduction: `Write a brief, warm response to someone introducing themselves.\n\nTheir email: ${reply.body}\n\nThank them for the introduction and express openness to connecting.`,
        support_request: `Write a brief, helpful response to a support request.\n\nTheir email: ${reply.body}\n\nAcknowledge their request and let them know we've received it and will follow up.`,
        other: `Write a brief, professional response to this email.\n\nTheir email: ${reply.body}\n\nThank them for their email and let them know we'll review and get back to them.`,
      };

      const promptInstruction = promptMap[analysis.classification];
      if (promptInstruction) {
        // Determine the "from" email: use the master agent's configured email account,
        // or fall back to the email listener config's linked email account
        let fromEmail: string | undefined;
        const agentConfig = maConfig;
        const configuredEmailAccountId = agentConfig.emailAccountId as string | undefined;
        if (configuredEmailAccountId) {
          const [emailAccount] = await withTenant(this.tenantId, async (tx) => {
            return tx.select().from(emailAccounts)
              .where(and(eq(emailAccounts.id, configuredEmailAccountId), eq(emailAccounts.tenantId, this.tenantId), eq(emailAccounts.isActive, true)))
              .limit(1);
          });
          if (emailAccount) fromEmail = emailAccount.fromEmail;
        }

        // Fall back to the listener config's linked email account
        if (!fromEmail) {
          const [listenerCfg] = await withTenant(this.tenantId, async (tx) => {
            return tx.select().from(emailListenerConfigs)
              .where(and(eq(emailListenerConfigs.tenantId, this.tenantId), eq(emailListenerConfigs.isActive, true)))
              .limit(1);
          });
          if (listenerCfg?.emailAccountId) {
            const [listenerEmailAccount] = await withTenant(this.tenantId, async (tx) => {
              return tx.select().from(emailAccounts)
                .where(and(eq(emailAccounts.id, listenerCfg.emailAccountId!), eq(emailAccounts.tenantId, this.tenantId)))
                .limit(1);
            });
            if (listenerEmailAccount) fromEmail = listenerEmailAccount.fromEmail;
          }
        }

        if (fromEmail) {
          const sent = await this.sendAutoResponse({
            masterAgentId,
            fromEmail,
            toEmail: reply.fromEmail,
            subject: reply.subject,
            contactId: contactId ?? undefined,
            replyBody: reply.body ?? '',
            promptInstruction,
          });
          if (sent) actionTaken = `${analysis.classification}_responded`;
        } else {
          logger.warn({ tenantId: this.tenantId, replyId }, 'No email account configured — skipping inbound auto-response');
        }
      }
    }

    // CRM actions based on classification
    if (contactId && analysis.classification !== 'spam') {
      try {
        const dealResult = await ensureDeal({ tenantId: this.tenantId, contactId, masterAgentId });

        if (analysis.classification === 'inquiry' || analysis.classification === 'application') {
          const repliedStage = await findStageBySlug(this.tenantId, 'replied');
          if (repliedStage) {
            await moveDealStage({ tenantId: this.tenantId, dealId: dealResult.id, newStageId: repliedStage.id, masterAgentId });
          }
        }
      } catch (err) {
        logger.warn({ err, contactId }, 'Failed to update CRM for inbound email');
      }
    }

    // Log CRM activity
    if (contactId) {
      try {
        await logActivity({
          tenantId: this.tenantId,
          contactId,
          masterAgentId,
          type: 'email_received',
          title: `Inbound classified as: ${analysis.classification}`,
          metadata: {
            replyId,
            classification: analysis.classification,
            sentiment: analysis.sentiment,
            priority: analysis.priority,
            senderName: analysis.senderName,
            senderCompany: analysis.senderCompany,
          },
        });
      } catch (err) {
        logger.warn({ err, contactId }, 'Failed to log inbound CRM activity');
      }
    }

    await this.emitEvent('email:inbound_classified', {
      replyId,
      contactId,
      classification: analysis.classification,
      sentiment: analysis.sentiment,
      priority: analysis.priority,
    });

    this.logActivity('inbound_classified', 'completed', {
      inputSummary: reply.fromEmail ?? replyId,
      details: { replyId, classification: analysis.classification, sentiment: analysis.sentiment, actionTaken },
    });
    await this.clearCurrentAction();

    logger.info({ tenantId: this.tenantId, replyId, classification: analysis.classification }, 'General inbound email classified');

    return {
      classification: analysis.classification,
      sentiment: analysis.sentiment,
      priority: analysis.priority,
      actionTaken,
    };
  }
}
